# Generated by Django 3.0.7 on 2020-07-02 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0002_specs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specs',
            new_name='Spec',
        ),
    ]
