# Generated by Django 3.0.7 on 2020-07-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0004_spec_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='display_size',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
