# Generated by Django 3.0.7 on 2020-07-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0005_auto_20200703_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='model',
        ),
        migrations.RemoveField(
            model_name='spec',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='spec',
            name='storage',
        ),
        migrations.AddField(
            model_name='spec',
            name='display_resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spec',
            name='os',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.CreateModel(
            name='Varient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobiles.Model')),
            ],
        ),
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.Model')),
            ],
        ),
        migrations.AddField(
            model_name='spec',
            name='Varient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobiles.Varient'),
        ),
    ]
