# Generated by Django 3.0.7 on 2020-07-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0006_auto_20200703_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spec',
            old_name='Varient',
            new_name='varient',
        ),
    ]
