# Generated by Django 3.0.7 on 2020-07-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0007_auto_20200703_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobiles.Model'),
        ),
    ]
