# Generated by Django 3.0.7 on 2020-07-05 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobiles', '0010_model_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=100)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.Model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.Model')),
            ],
        ),
        migrations.CreateModel(
            name='RecentMobiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.Model')),
            ],
        ),
        migrations.CreateModel(
            name='RecentComparisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmodel1', to='mobiles.Model')),
                ('mobile2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmodel2', to='mobiles.Model')),
            ],
        ),
        migrations.CreateModel(
            name='PopularMobiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.Model')),
            ],
        ),
        migrations.CreateModel(
            name='PopularComparisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmodel1', to='mobiles.Model')),
                ('mobile2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmodel2', to='mobiles.Model')),
            ],
        ),
    ]
