# Generated by Django 3.0.7 on 2020-07-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0012_auto_20200705_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentsearch',
            name='search',
            field=models.CharField(max_length=60),
        ),
    ]
