# Generated by Django 3.0.7 on 2020-07-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0013_auto_20200705_0916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentSearch',
        ),
    ]
