# Generated by Django 3.0.7 on 2020-07-06 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0016_auto_20200707_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='avg_rating',
        ),
    ]
